<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ManualTradeBot.Core\ManualTradeBot.Core.csproj" />
    <Reference Include="TradingPlatform.BusinessLayer">
      <HintPath>C:\Quantower\TradingPlatform\v1.146.16\bin\TradingPlatform.BusinessLayer.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
